# Generated by Django 4.0.4 on 2022-08-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import road_map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('L', 'Leaf'), ('O', 'Or'), ('A', 'And')], max_length=1)),
                ('background', models.ImageField(upload_to=road_map.models.page_background_path)),
                ('icon', models.ImageField(upload_to=road_map.models.page_icon_path)),
                ('importance_and_advantages', models.TextField()),
                ('advice_and_tools', models.TextField()),
                ('reference_next_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_parents', to='road_map.page')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_children', to='road_map.page')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='road_map.page')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='road_map.page')),
            ],
            options={
                'unique_together': {('page', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('link', models.URLField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='road_map.page')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='road_map.feature')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='road_map.reference')),
            ],
            options={
                'unique_together': {('reference', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='FinishedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_users', to='road_map.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('page', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependency_parents', to='road_map.page')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_children', to='road_map.page')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
