# Generated by Django 4.0.4 on 2022-07-29 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('L', 'Leaf'), ('O', 'Or'), ('A', 'And')], max_length=1)),
                ('background', models.ImageField(upload_to='backgrounds')),
                ('icon', models.ImageField(upload_to='icons')),
                ('view_template', models.TextField(null=True)),
                ('importance_and_advantages', models.TextField()),
                ('advice_and_tools', models.TextField()),
                ('dependencies', models.ManyToManyField(related_name='related_dependencies', to='road_map.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageReferencesFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page')),
            ],
            options={
                'db_table': 'road_map_page_references_feature',
            },
        ),
        migrations.CreateModel(
            name='PageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('features', models.ManyToManyField(related_name='page_references', through='road_map.Feature', to='road_map.pagereferencesfeature')),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_children_set', to='road_map.page')),
                ('referenced_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_parent_set', to='road_map.page')),
            ],
            options={
                'db_table': 'road_map_page_reference',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='references',
            field=models.ManyToManyField(related_name='related_references', through='road_map.PageReference', to='road_map.page'),
        ),
        migrations.CreateModel(
            name='FinishedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='page_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_set', to='road_map.pagereference'),
        ),
        migrations.AddField(
            model_name='feature',
            name='page_references_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_set', to='road_map.pagereferencesfeature'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('link', models.URLField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page')),
            ],
        ),
    ]
