# Generated by Django 4.0.4 on 2022-07-12 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('L', 'Leaf'), ('O', 'Or'), ('A', 'And')], max_length=1)),
                ('background', models.ImageField(upload_to='')),
                ('icon', models.ImageField(upload_to='')),
                ('view_template', models.TextField(null=True)),
                ('importance_and_advantages', models.TextField()),
                ('advice_and_tools', models.TextField()),
                ('dependencies', models.ManyToManyField(related_name='related_dependencies', to='road_map.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageReferencesFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_children_set', to='road_map.page')),
                ('referenced_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_parent_set', to='road_map.page')),
            ],
            options={
                'db_table': 'road_map_page_references',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='references',
            field=models.ManyToManyField(related_name='related_references', through='road_map.PageReference', to='road_map.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='students',
            field=models.ManyToManyField(through='road_map.FinishedPage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page'),
        ),
        migrations.AddField(
            model_name='finishedpage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('page_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.pagereference')),
                ('page_references_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.pagereferencesfeatures')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('link', models.URLField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_map.page')),
            ],
        ),
    ]
