# Generated by Django 4.0.4 on 2022-07-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageReferencesFeatures',
            new_name='PageReferencesFeature',
        ),
        migrations.AlterModelTable(
            name='pagereference',
            table='road_map_page_reference',
        ),
        migrations.AlterModelTable(
            name='pagereferencesfeature',
            table='road_map_page_references_feature',
        ),
    ]
