# Generated by Django 4.1 on 2022-08-16 15:48

from django.db import migrations, models
import road_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background',
            field=models.ImageField(max_length=500, upload_to=road_map.models.page_background_path),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.ImageField(max_length=500, upload_to=road_map.models.page_icon_path),
        ),
    ]
