# Generated by Django 4.0.4 on 2022-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='reference_next_index',
            field=models.IntegerField(default=0),
        ),
    ]
