# Generated by Django 4.0.4 on 2022-07-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0002_rename_pagereferencesfeatures_pagereferencesfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereference',
            name='features',
            field=models.ManyToManyField(related_name='page_references', through='road_map.Feature', to='road_map.pagereferencesfeature'),
        ),
    ]
