# Generated by Django 4.0.4 on 2022-08-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0002_page_reference_next_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='view_template',
        ),
    ]
