# Generated by Django 4.0.4 on 2022-08-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0003_remove_page_view_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('parent', 'child')},
        ),
    ]
