# Generated by Django 4.0.4 on 2022-07-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0004_alter_feature_page_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='students',
        ),
    ]
