# Generated by Django 4.0.4 on 2022-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0004_alter_reference_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencefeature',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
