# Generated by Django 4.0.4 on 2022-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_map', '0005_remove_page_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background',
            field=models.ImageField(upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.ImageField(upload_to='icons'),
        ),
    ]
