# Generated by Django 4.0.4 on 2022-08-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forum',
            name='closed_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_forum', to='forum.reply'),
        ),
    ]
