# Generated by Django 4.0.4 on 2022-07-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_is_closed_alter_reply_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='closed_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.reply'),
        ),
    ]
