# Generated by Django 4.0.4 on 2022-08-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_points_alter_forum_closed_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
