# Generated by Django 4.0.4 on 2022-08-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='closed_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_forum', to='forum.reply'),
        ),
    ]
