# Generated by Django 4.0.4 on 2022-08-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voteditem',
            index=models.Index(fields=['content_type', 'object_id'], name='vote_votedi_content_519dc8_idx'),
        ),
    ]
