# Generated by Django 4.0.4 on 2022-08-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_of_uses', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_add', models.BooleanField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tag.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_tags', to='tag.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='suggestedtag',
            index=models.Index(fields=['content_type', 'object_id'], name='tag_suggest_content_3dc4ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suggestedtag',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='appliedtag',
            index=models.Index(fields=['content_type', 'object_id'], name='tag_applied_content_56582d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedtag',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
