# Generated by Django 4.0.4 on 2022-08-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appliedtag',
            index=models.Index(fields=['content_type', 'object_id'], name='tag_applied_content_56582d_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedtag',
            index=models.Index(fields=['content_type', 'object_id'], name='tag_suggest_content_3dc4ee_idx'),
        ),
    ]
