# Generated by Django 4.0.4 on 2022-07-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_name_alter_suggestedtag_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
    ]
