# Generated by Django 4.0.4 on 2022-08-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_appliedtag_tag_applied_content_56582d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_tags', to='tag.tag'),
        ),
    ]
