# Generated by Django 4.0.4 on 2022-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_remove_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number_of_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
