# Generated by Django 4.0.4 on 2022-07-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_alter_tag_number_of_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tag.tag'),
        ),
    ]
