# Generated by Django 4.0.4 on 2022-07-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tag', '0005_alter_suggestedtag_tag_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggedItem',
            new_name='AppliedTag',
        ),
    ]
