# Generated by Django 4.0.4 on 2022-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
