# Generated by Django 4.0.4 on 2022-08-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
