# Generated by Django 4.0.4 on 2022-07-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='end_date',
            new_name='graduate_date',
        ),
    ]
