# Generated by Django 4.1 on 2022-08-16 15:45

from django.db import migrations, models
import student_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_alter_contact_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=student_profile.models.profile_photo_path),
        ),
    ]
