# Generated by Django 4.0.4 on 2022-07-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_rename_end_date_profile_graduate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
