# Generated by Django 4.0.4 on 2022-07-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_rename_data_mark_date_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('profile', 'project')},
        ),
    ]
