# Generated by Django 4.1 on 2022-08-16 15:48

from django.db import migrations, models
import student_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=student_profile.models.project_photo_path),
        ),
    ]
