# Generated by Django 4.0.4 on 2022-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_projectfeature_tool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFeature',
            new_name='Feature',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='project_feature',
            new_name='feature',
        ),
    ]
