# Generated by Django 4.0.4 on 2022-08-01 01:30

from django.db import migrations, models
import student_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=student_profile.models.profile_photo_path),
        ),
    ]
