# Generated by Django 4.0.4 on 2022-08-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_rename_projectfeature_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='feature',
        ),
        migrations.CreateModel(
            name='FeatureTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_tools', to='student_profile.feature')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_features', to='student_profile.tool')),
            ],
        ),
    ]
