# Generated by Django 4.0.4 on 2022-07-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_alter_contact_profile_alter_experience_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_graduated',
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
