# Generated by Django 4.0.4 on 2022-08-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0005_remove_tool_description_remove_tool_feature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_cerified',
            new_name='is_certified',
        ),
    ]
