# Generated by Django 4.0.4 on 2022-08-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0006_rename_is_cerified_project_is_certified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='position',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='student_profile.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='student_profile.project')),
            ],
        ),
    ]
