# Generated by Django 4.0.4 on 2022-08-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0007_remove_project_position_remove_project_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('profile', 'project')},
        ),
    ]
