# Generated by Django 4.0.4 on 2022-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion
import student_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0008_alter_membership_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(null=True, upload_to=student_profile.models.project_photo_path),
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='student_profile.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='student_profile.project')),
            ],
            options={
                'unique_together': {('profile', 'project')},
            },
        ),
    ]
