# Generated by Django 4.0.4 on 2022-08-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0010_project_projects_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='profiles',
            field=models.ManyToManyField(related_name='projects', through='student_profile.Membership', to='student_profile.profile'),
        ),
    ]
