# Generated by Django 4.0.4 on 2022-08-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0011_remove_project_projects_project_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profiles',
        ),
    ]
