# Generated by Django 4.0.4 on 2022-08-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0012_remove_project_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profiles',
            field=models.ManyToManyField(related_name='projects', through='student_profile.Membership', to='student_profile.profile'),
        ),
    ]
