# Generated by Django 4.0.4 on 2022-08-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0014_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
