# Generated by Django 4.0.4 on 2022-08-13 17:50

from django.db import migrations, models
import student_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0015_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=student_profile.models.project_photo_path),
        ),
    ]
